sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness
sonar.host.url=http://localhost:9000
sonar.login=sqp_4ff5d24929c97925ac4e5c5a0ca6f918e0c43501

sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8